name: rcpr
on:
  push:
    branches:
    - "main"
jobs:
  rcpr:
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v3
    - run: |
        go install github.com/Songmu/rcpr/cmd/rcpr@latest
        rcpr
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
